export enum charactersActionTypes {
  GET_CHARACTERS = 'GET_CHARACTERS',
  SET_CHARACTERS = 'SET_CHARACTERS',
  GET_CHARACTER_BY_ID = 'GET_CHARACTER_BY_ID',
  SET_CHARACTER_BY_ID = 'SET_CHARACTER_BY_ID',
  SET_FAVORITE_CHARACTER = 'SET_FAVORITE_CHARACTER'
}
